# Generated by Django 2.2.9 on 2019-12-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
