# Generated by Django 2.2.9 on 2019-12-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_auto_20191226_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
