# Generated by Django 2.2.9 on 2019-12-26 21:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_remove_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79876543213', max_length=128, region=None, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
