# Generated by Django 2.2.9 on 2020-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_auto_20191227_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avito',
            field=models.URLField(blank=True, verbose_name='профиль на Avito'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youla',
            field=models.URLField(blank=True, verbose_name='профиль на Юле'),
        ),
    ]
