# Generated by Django 2.2.9 on 2020-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200114_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemonmainpage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='itemonmainpage',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
