# Generated by Django 2.2.9 on 2020-01-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200114_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemonmainpage',
            options={'ordering': ['position'], 'verbose_name': 'товар на главной', 'verbose_name_plural': 'товары на главной'},
        ),
    ]
