# Generated by Django 2.2.9 on 2020-01-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20200124_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemonmainpage',
            name='position',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=10),
        ),
    ]
