# Generated by Django 2.2.10 on 2020-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20200126_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemonmainpage',
            name='position',
            field=models.IntegerField(),
        ),
    ]
