# Generated by Django 3.0 on 2019-12-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='название',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='описание',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='цена',
        ),
    ]
