# Generated by Django 3.0 on 2019-12-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20191214_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='название',
        ),
    ]
