# Generated by Django 2.2.9 on 2019-12-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_auto_20191219_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='длинна описания не может превышать 500 символов', max_length=500, verbose_name='описание'),
        ),
    ]
