# Generated by Django 2.2.9 on 2019-12-28 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=500, verbose_name=django.core.validators.MinLengthValidator(100)),
        ),
    ]
