# Generated by Django 2.2.9 on 2019-12-28 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0025_auto_20191228_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='длинна описания не может превышать 500 символов', max_length=500, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='описание'),
        ),
    ]
