# Generated by Django 2.2.9 on 2020-01-09 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0026_auto_20191228_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='длинна описания должна быть от 100 до 500 символов', max_length=500, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items', verbose_name='изображение'),
        ),
    ]
