# Generated by Django 2.2.10 on 2020-05-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(choices=[('F08080', 'Green'), ('32CD32', 'Yellow')], default='00FFFF', max_length=6)),
            ],
        ),
    ]
