# Generated by Django 2.2.10 on 2020-05-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    def set_colors(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        ColorTheme = apps.get_model('color_theme', 'ColorTheme')
        ColorTheme.objects.create(colors='#30373e #f5f8e9')

    dependencies = [
        ('color_theme', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_colors)
    ]
