# Generated by Django 2.2.10 on 2020-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_theme', '0002_auto_20200521_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colortheme',
            name='colors',
            field=models.CharField(choices=[('#F08080 #32CD32', 'Greenw'), ('#32CD32 #F08080', 'Yellow')], max_length=6),
        ),
    ]
