# Generated by Django 2.2.10 on 2020-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_theme', '0003_auto_20200522_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colortheme',
            name='colors',
            field=models.CharField(choices=[('#30373e #f5f8e9', 'Classic'), ('#32cd66 #32cd66', 'Just Green'), ('#4682B4 #00CED1', 'Aqua'), ('#BA55D3 #EE82EE', 'Violet'), ('#000080 #0000FF', 'Navy Blue'), ('#DC143C #FF0000', 'Fire Red'), ('#f36767 #F08080', 'Too Pink'), ('#fa7218 #f28659', 'Very Orange'), ('#F08080 #32CD32', 'Pink-Green'), ('#32CD32 #F08080', 'Green-Pink')], max_length=15, verbose_name='Выберите цветовую схему сайта'),
        ),
    ]
