# Generated by Django 2.2.10 on 2020-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_manager', '0002_auto_20200318_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(error_messages={'unique': 'Категория с таким названием уже существует!'}, max_length=20, unique=True, verbose_name='Название категории'),
        ),
    ]
