# Generated by Django 2.2.10 on 2020-04-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_manager', '0003_auto_20200318_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'категории'},
        ),
    ]
