# Generated by Django 2.2.9 on 2019-12-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20191224_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль'},
        ),
    ]
