# Generated by Django 2.2.9 on 2019-12-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20191224_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
