# Generated by Django 2.2.9 on 2019-12-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
