# Generated by Django 2.2.9 on 2019-12-27 18:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_auto_20191227_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+79615917361', max_length=128, region=None, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
