# Generated by Django 2.2.9 on 2020-01-11 19:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_auto_20200109_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avito',
            field=models.URLField(blank=True, help_text='Оставьте поле пустым, чтобы не отображать ссылку в футере.', verbose_name='профиль на Avito'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Без номера телефона кнопки "Позвонить" и "WhatsApp" не активны.', max_length=128, region=None, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='youla',
            field=models.URLField(blank=True, help_text='Оставьте поле пустым, чтобы не отображать ссылку в футере.', verbose_name='профиль на Юле'),
        ),
    ]
