# Generated by Django 2.2.10 on 2020-04-22 13:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0044_auto_20200420_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branding',
            field=models.CharField(default='Главная', help_text='help_text', max_length=50, verbose_name='verbose_name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='messenger',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='whatsapp', help_text='Выберите в какой мессенджер перенаправлять пользователя.', max_length=10, verbose_name='Мессенджер для связи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n        Без номера телефона кнопки "Позвонить" и "WhatsApp" не активны.\n        ', max_length=128, region=None, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_user_link',
            field=models.URLField(blank=True, help_text='\n        Заполните поле если используете Telegram\n        в качестве мессенджера для связи.\n        ', verbose_name='Ссылка на Telegram UserName'),
        ),
    ]
