# Generated by Django 2.2.10 on 2020-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0046_auto_20200422_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branding',
            field=models.CharField(default='Главная', help_text='Этот текст будет отображаться вместо\n        кнопки "Главная" в навигацилнной панели сайта', max_length=20, verbose_name='Брендирование витрины'),
        ),
    ]
