# Generated by Django 2.2.9 on 2020-01-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0045_auto_20200114_0922'),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOnMainPage_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_on_main_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showcase.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemOnMainPage',
        ),
    ]
