# Generated by Django 2.2.9 on 2020-01-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0045_auto_20200114_0922'),
        ('mainpage', '0002_auto_20200114_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOnMainPage_1',
            new_name='ItemOnMainPage',
        ),
    ]
