# Generated by Django 2.2.9 on 2020-01-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20200114_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemonmainpage',
            name='item_on_main_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showcase.Item', verbose_name='Товар на главной'),
        ),
        migrations.AlterField(
            model_name='itemonmainpage',
            name='position',
            field=models.IntegerField(),
        ),
    ]
