# Generated by Django 3.0 on 2019-12-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20191214_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='название',
            new_name='tetetetetette',
        ),
    ]
