# Generated by Django 3.0 on 2019-12-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_auto_20191214_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tetetetetette',
            new_name='title',
        ),
    ]
