# Generated by Django 3.0 on 2019-12-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_auto_20191214_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='описание объявления'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=20, verbose_name='название объявления'),
        ),
    ]
