# Generated by Django 3.0 on 2019-12-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='', verbose_name='изображение'),
        ),
    ]
