# Generated by Django 2.2.9 on 2019-12-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_auto_20191225_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
    ]
