# Generated by Django 2.2.9 on 2020-01-11 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0036_auto_20200111_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sort_position',
            field=models.IntegerField(default=0, help_text='Выберете позицию товара на главной (от 1 до 9).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Позиция на главной'),
        ),
    ]
