# Generated by Django 2.2.9 on 2020-01-11 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0037_auto_20200111_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sort_position',
            field=models.IntegerField(blank=True, help_text='Выберете позицию товара на главной (от 1 до 9).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Позиция на главной'),
        ),
    ]
