# Generated by Django 2.2.10 on 2020-03-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0046_auto_20200306_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория товара'},
        ),
    ]
