# Generated by Django 2.2.9 on 2019-12-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_remove_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Xiaomi', help_text='длинна названия не может превышать 20 символов', max_length=20, verbose_name='название'),
            preserve_default=False,
        ),
    ]
