# Generated by Django 2.2.9 on 2020-01-11 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0031_auto_20200111_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sort_position',
            field=models.IntegerField(default=10, help_text='Выберете позицию товара на главной (от 1 до 9).', max_length=9, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция на главной'),
        ),
    ]
