# Generated by Django 2.2.9 on 2020-01-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0044_auto_20200114_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pub_date'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sort_position',
        ),
    ]
