# Generated by Django 2.2.10 on 2020-03-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0047_auto_20200306_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Категория товара'),
        ),
    ]
