# Generated by Django 2.2.10 on 2020-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0049_auto_20200306_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='Формат изображения должен быть 1×1,\n        рекомендуемое разрешение 600×600 пикселей. Размер\n        изображения не должен превышать 1 мегабайт', upload_to='item_images', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Длинна названия не должна превышать 30 символов.', max_length=30, verbose_name='название'),
        ),
    ]
