# Generated by Django 2.2.10 on 2020-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0050_auto_20200508_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='Формат изображения должен быть 1×1,\n        рекомендуемое разрешение 600×600 пикселей. Размер\n        изображения не должен превышать 1 мегабайт.', upload_to='item_images', verbose_name='изображение'),
        ),
    ]
