# Generated by Django 2.2.10 on 2020-05-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0051_auto_20200508_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='В архив?'),
        ),
    ]
