# Generated by Django 2.2.10 on 2020-05-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0052_item_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, help_text='Архивированные товары не отображаются посетителям сайта.', verbose_name='Поместить товар в архив'),
        ),
    ]
