# Generated by Django 2.2.10 on 2020-06-10 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0053_auto_20200512_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Длинна описания должна быть от 100 до 500 символов.', max_length=500, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='описание'),
        ),
    ]
