# Generated by Django 2.2.13 on 2020-06-15 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0054_auto_20200610_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Длинна описания не должна превышать 500 символов.', max_length=500, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='описание'),
        ),
    ]
