# Generated by Django 2.2.13 on 2020-06-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0055_auto_20200615_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Длинна описания не должна превышать 500 символов.', max_length=500, verbose_name='описание'),
        ),
    ]
