# Generated by Django 2.2.9 on 2019-12-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
