# Generated by Django 2.2.10 on 2020-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_auto_20200406_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.URLField(blank=True, help_text='Оставьте поле пустым, чтобы не отображать ссылку в футере.', verbose_name='профиль Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Оставьте поле пустым, чтобы не отображать ссылку в футере.', verbose_name='профиль WhatsApp'),
        ),
    ]
