# Generated by Django 2.2.10 on 2020-04-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0038_auto_20200412_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messanger',
            name='telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messanger',
            name='viber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messanger',
            name='whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
