# Generated by Django 2.2.10 on 2020-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_auto_20200412_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messanger',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_boolen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='viber_boolen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_boolen',
            field=models.BooleanField(default=True),
        ),
    ]
