# Generated by Django 2.2.10 on 2020-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0040_auto_20200412_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_boolen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='viber_boolen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='whatsapp_boolen',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messanger',
            field=models.CharField(default='whatsapp', max_length=50),
        ),
    ]
