# Generated by Django 2.2.10 on 2020-04-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0041_auto_20200412_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='messanger',
            new_name='messenger',
        ),
    ]
