# Generated by Django 2.2.10 on 2020-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0042_auto_20200412_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_user_link',
            field=models.URLField(blank=True, help_text='Оставьте поле пустым, чтобы не отображать ссылку в футере.', verbose_name='профиль Telegram'),
        ),
    ]
