# Generated by Django 2.2.10 on 2020-04-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0043_userprofile_telegram_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='messenger',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='whatsapp', help_text='Выберите в какой мессенджер перенаправлять пользователя', max_length=10, verbose_name='Мессенджер для связи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_user_link',
            field=models.URLField(blank=True, help_text='Заполните поле если используете Telegram в качестве мессенджера для связи.', verbose_name='Ссылка на Telegram UserName'),
        ),
    ]
