# Generated by Django 2.2.10 on 2020-04-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0050_auto_20200422_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('₽', 'Российский рубль'), ('Br', 'Белорусский рубль'), ('₴', 'Украинская гривна'), ('$', 'Доллар'), ('€', 'Евро')], default='₽', help_text='TEST', max_length=1, verbose_name='TEST'),
        ),
    ]
