# Generated by Django 2.2.10 on 2020-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0052_auto_20200422_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('₽', 'Российский рубль - ₽'), ('Br', 'Белорусский рубль - Br'), ('₴', 'Украинская гривна - ₴'), ('$', 'Доллар - $'), ('€', 'Евро - €')], default='₽', help_text='Символ выбранной валюты будет отображаться в карточках товаров.', max_length=2, verbose_name='Валюта'),
        ),
    ]
