# Generated by Django 2.2.10 on 2020-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0053_auto_20200422_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='brand',
            field=models.CharField(default='Главная', help_text='Этот текст будет отображаться вместо\n        кнопки "Главная" в навигационной панели сайта.', max_length=25, verbose_name='Брендирование витрины'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('₽', 'Российский рубль - ₽'), ('Br', 'Белорусский рубль - Br'), ('₴', 'Украинская гривна - ₴'), ('$', 'Доллар - $'), ('€', 'Евро - €')], default='₽', help_text='Символ выбранной валюты будет отображаться\n        в карточках товаров.', max_length=2, verbose_name='Валюта'),
        ),
    ]
