# Generated by Django 2.2.10 on 2020-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0054_auto_20200508_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='market',
            field=models.URLField(blank=True, help_text='Оставьте поле пустым, чтобы не отображать ссылку в футере.', verbose_name='профиль на торговой площадке("Юла", "Avito и т.д.").'),
        ),
    ]
